### ISSUE TITLE
redis example error

### ISSUE THREAD

**Issue by januwA** [actix/examples#550]
https://github.com/actix/examples/blob/master/databases/redis/Cargo.toml

This example no longer works with `actix = "0.13"`

```
error[E0277]: the trait bound `RedisActor: actix::Actor` is not satisfied
  --> src/controller/api/book.rs:34:22
   |
34 |     redis: web::Data<Addr<RedisActor>>,
   |                      ^^^^^^^^^^^^^^^^ the trait `actix::Actor` is not implemented for `RedisActor`
   |
note: required by a bound in `actix::Addr`
  --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/actix-0.13.0/src/address/mod.rs:76:20
   |
76 | pub struct Addr<A: Actor> {
   |                    ^^^^^ required by this bound in `actix::Addr`

For more information about this error, try `rustc --explain E0277`.
```

**Comment by robjtede** [comment]
yes, it needs to use `actix = "0.12"` so that the types are compatible
