### ISSUE TITLE
middleware example doesn't work in rustc 1.46.0-nightly 

### ISSUE THREAD

**Issue by jellybobbin** [actix/examples#356]
### example middlewaere doesn't work:
[read_response_body.rs](https://github.com/actix/examples/blob/master/middleware/src/read_response_body.rs)

### rustc:
```
rustc 1.46.0-nightly 
```

### error:
```rust
error[E0053]: method `poll_next` has an incompatible type for trait
   --> src/app/http/middleware/read_response_body.rs:105:5
    |
105 |     fn poll_next(&mut self, cx: &mut Context<'_>) -> Poll<Option<Result<Bytes, Error>>> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::pin::Pin`, found mutable reference
    |
    = note: expected fn pointer `fn(std::pin::Pin<&mut app::http::middleware::read_response_body::BodyLogger<B>>, &mut std::task::Context<'_>) -> std::task::Poll<_>`
               found fn pointer `fn(&mut app::http::middleware::read_response_body::BodyLogger<B>, &mut std::task::Context<'_>) -> std::task::Poll<_>`

error[E0599]: no method named `poll_next` found for enum `actix_web::dev::ResponseBody<B>` in the current scope
   --> src/app/http/middleware/read_response_body.rs:106:25
    |
106 |         match self.body.poll_next(cx) {
    |                         ^^^^^^^^^ method not found in `actix_web::dev::ResponseBody<B>`

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/app/http/middleware/read_response_body.rs:107:33
    |
107 |             Poll::Ready(Some(Ok(chunk))) => {
    |                                 ^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/app/http/middleware/read_response_body.rs:107:30
    |
107 |             Poll::Ready(Some(Ok(chunk))) => {
    |                              ^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required by `controllers::demo::demo_controller::_::_serde::export::Ok`

error[E0308]: mismatched types
   --> src/app/http/middleware/read_response_body.rs:109:37
    |
109 |                 Poll::Ready(Some(Ok(chunk)))
    |                                     ^^^^^ expected struct `bytes::Bytes`, found slice `[u8]`

error: aborting due to 5 previous errors; 3 warnings emitted

Some errors have detailed explanations: E0053, E0277, E0308, E0599.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `wedoc`.

To learn more, run the command again with --verbose.

Process finished with exit code 101
```
