### PR TITLE
Fix for build failure in diesel example

### LINKED ISSUE #354: diesel example fails to build
While attempting to build the diesel example, the build fails with:
```
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /home/shane/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.6/src/lib.rs:107:70
    |
107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
    |                                                                      ^^^^ could not find `__rt` in `quote`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `failure_derive`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

From Googling, this appears to be an issue with the `failure` dependency. See https://github.com/rust-lang-nursery/failure/issues/342 for reference.

I'll submit a PR shortly with a fix.

### PR DESCRIPTION
**Pull request by thesurlydev**
Closes #354

### CODE REVIEW

**Comment by JohnTitor** [comment]
Well, I don't think it should be added here as some may be confused by it, "why is there an unused dependency?". The failure v0.1.8, which has a fix for it, was released in May and the users should get the newest version in the future so it won't be a major issue here, I assume. I'd like to get rid of it or add a comment that explains the issue at least.

**Comment by robjtede** [comment]
It will be removed soon when we upgrade examples to v3 anyway.
